print(f"#"*36)
print("#                                  #")
print("#     Muhammad Chairur Rijal       #")
print("#         21108171100009           #")
print("#                                  #")
print(f"#"*36)