nm = input ("Nama\t :")
nim = input ("NIM\t :")
kls = input ("Kelas Pararel\t :")
ttl = input ("Tempat/Tanggal Lahir\t :")
almt = input ("Alamat\t :")
hobi = input ("Hobby\t :")
hp = input ("No. HP\t :")

print("-------------------------------------------\n")
print("Nama\t\t\t :", nm)
print("NIM\t\t\t :", nim)
print("Kelas Pararel\t\t : ", kls)
print("Tempat/Tanggal Lahir\t :", ttl)
print("Alamat\t\t\t :", almt)
print("Hobby\t\t\t :", hobi)
print("No. HP\t\t\t :", hp)